<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="F_IN_BOUNDS_ARRAY_INT" Id="{e02df47f-0dea-4eec-9512-43a537103fc1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_IN_BOUNDS_ARRAY_INT : BOOL
VAR_INPUT
	index		: DINT;
END_VAR
VAR_IN_OUT
	arrayIn		: ARRAY[*] OF INT;
END_VAR
VAR
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_IN_BOUNDS_ARRAY_INT := index <= UPPER_BOUND(arrayIn, 1) AND index >= LOWER_BOUND(arrayIn, 1);
]]></ST>
    </Implementation>
    <LineIds Name="F_IN_BOUNDS_ARRAY_INT">
      <LineId Id="21" Count="0" />
      <LineId Id="18" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>