<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="UnitTests" Id="{6e2183c7-16a4-43f8-8211-71db06d79010}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM UnitTests
VAR
	fbTestRound		: Fb_TestRound;
	fbTestSplit		: FB_TestSplit;
	fbTestRange		: FB_TestRange;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
    <LineIds Name="UnitTests">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>